CREATE OR REPLACE FUNCTION F_LANZA_PROCESO (strOBJID_CONTRACT VARCHAR2, strNAME_PROCESS VARCHAR2, strVERSION_PROCESS VARCHAR2)
RETURN VARCHAR2 AS EXTERNAL
LIBRARY LIB_LANZAPROCESO
NAME "main"
LANGUAGE C;

 
