CREATE OR REPLACE FUNCTION F_LANZAR_PROCINST(strOBJID_CONTRACT VARCHAR2, strNAME_PROCESS VARCHAR2, strVERSION_PROCESS VARCHAR2) RETURN VARCHAR2 AS

  strRETURN VARCHAR2(31) := '';


BEGIN
  
  strRETURN := F_LANZAR_PROCINST(strOBJID_CONTRACT, strNAME_PROCESS, strVERSION_PROCESS);
  
  IF LENGTH(strRETURN) > 0 THEN
     DBMS_OUTPUT.PUT_LINE('PROCESO LANZADO CORRECTAMENTE: ' || strRETURN);    
  ELSE
    DBMS_OUTPUT.PUT_LINE('OCURRIO UN ERROR AL LANZAR EL PROCESO ' || strNAME_PROCESS || '(' || strVERSION_PROCESS || ')');    
  
  END IF;


EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('ERROR ' || SQLERRM);
  
END;
